version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "daily"

  - package-ecosystem: "elixir:hex"
    directory: "/"
    schedule:
      interval: "daily"
